### PR TITLE
Initial code

### PR DESCRIPTION
**Pull request by joellord**

### CODE REVIEW

**Comment by rbola** [comment]
@joellord quick overall feedback. 

- The example you provide is too similar to the already ranking tutorial: https://www.baeldung.com/mongodb-morphia
- Morphia is all about mapping Java entities to MongoDB Documents, meaning making it easy to find the App Model it is important. therefore I would advice to structure the project to have  the Model Classes( Book, Author) out of the App.java. Leave the App.java just with the main method and any private method that support your app.

Have a look on what Maxime did here: git clone https://github.com/mongodb-developer/java-quick-start (it is not using Morphia, but it is clear the separation between the model and the different CRUD operations)

**Review by rbola — CHANGES_REQUESTED** [review]
- Can you please remove the model classes out from the App.java?
-  The Books Model example is not  really showcasing that would justify the use of Morphia vs the PoJo mapping of our MongoDB Java driver (read this thread https://stackoverflow.com/questions/67403051/do-we-still-need-morphia-for-java to help you find that)

**Comment by MaBeuLux88** [comment]
Yeah Morphia was born before we had POJO mapping directly in the Java driver. I'm not sure why Morphia is still around today.

**Comment by joellord** [comment]
@rbola How about this new approach? I will highlight the referencing part as well as the annotation indexing. Would that make for a better story?

**Review by rbola — CHANGES_REQUESTED** [review]
Yes better example. Thank you for changing from books to recipes.
- Please Move the model classes out of the App.java
- Remove the use MorphiaReference.wrap (from https://morphia.dev/morphia/1.6/references.html, apologies I know I sent you that way on my last comment) because it seems to be still experimental. Use instead the normal @Reference explain here: https://morphia.dev/morphia/1.6/annotations.html

**Comment by joellord** [comment]
@rbola @MaBeuLux88 The article will highlight two use cases for Morphia. Creating DBRef's and how they are lazily fetched, and the Indexes creation using annotations. I think this code does a better job of showcasing those two features.

**Review by rbola — APPROVED** [review]
going on the right direction, thank you.

**Pull request closed without merging**
